title: Johnathan Oneal
email: johnjay2806@gmail.com
description: "Thanks for stopping by :)"
baseurl: "" 
url: "" 
github_username: JohnathanOneal

theme: minima
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
