title: Johnathan Oneal
email: johnjay2806@gmail.com
description: "Thanks for stopping by :)"
baseurl: "" 
url: "" 
github_username: JohnathanOneal

#theme: minima
plugins:
  - jekyll-feed

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year/:month/:day/:title/

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
