name: Update KenPom Data to S3

on:
  schedule:
    - cron: '0 10 * * *'  # Runs at 10:00 UTC every day (5:00 AM Eastern Time)
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas playwright boto3

    - name: Install Playwright Browsers
      run: playwright install

    - name: Fetch KenPom data and upload to S3
      env:
        KENPOM_USERNAME: ${{ secrets.KENPOM_USERNAME }}
        KENPOM_PASSWORD: ${{ secrets.KENPOM_PASSWORD }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      run: python docs/scripts/kenpom_pull.py --b 2010 --e 2025

    - name: Confirm S3 upload
      run: |
        echo "KenPom data has been uploaded to S3 bucket: ${{ secrets.S3_BUCKET_NAME }}"
        echo "Check the S3 bucket for the uploaded data file."

