name: Test PAT

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test PAT
      env:
        TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        echo "Testing PAT..."
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
        git status
