name: Test PAT

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test PAT
      env:
        TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        echo "Testing PAT..."
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
        git status
