name: Update WaniKani Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch WaniKani stats
      env:
        WANIKANI_API_KEY: ${{ secrets.WANIKANI_API_KEY }}
      run: python docs/scripts/wanikani.py

    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Debug Git Configuration
      run: |
        git remote -v
        git config --list

    - name: Commit and push if changed
      env:
        TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}  # Your secret PAT
      run: |
        git add docs/data/wanikani_stats.json
        git diff --quiet && git diff --staged --quiet || (
          git commit -m "Update WaniKani stats" && \
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git && \
          git push
        )
